<a href="https://colab.research.google.com/github/roannarum/Data-Practice/blob/main/Dewi_Arumsari_202103029.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Download data Iris dataset dari Kaggle, kemudian buat folder Dataset di Google drive dan upload ke Dataset/Iris.csv
. Link Dataset : https://www.kaggle.com/datasets/uciml/iris
2. Buka Google Colab dan Buat lembar kerja baru.
3. Koneksikan Google Drive dengan Google Colab.

In [ ]:
# Koneksikan ke Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


4. Import library yang diperlukan seperti pandas, numpy, seaborn, sklearn dan matplotlib.

Untuk sklearn import modul KNeighborsClassifier, 
LogisticRegression, GaussianNB dari Naive Bayes, train_test_split, accuracy_score, confusion_matrix.

In [ ]:
# Import library yang diperlukan
import pandas as pd
import numpy as np

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB



5. Panggil dataset bunga iri yang ada di Google Drive. Simpan pada variabel **data**.

In [ ]:
# Memanggil dataset bunga
data = pd.read_csv('/content/drive/MyDrive/Dataset/Iris.csv')

6. Tampilkan 10 dataset pertama.

In [ ]:
# Menampilkan 10 dataset 
data.head(10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

7. Tampilkan 10 dataset yang terakhir

In [ ]:
# Menampilkan 10 dataset terakhir
data.tail(10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
140  141            6.7           3.1            5.6           2.4   
141  142            6.9           3.1            5.1           2.3   
142  143            5.8           2.7            5.1           1.9   
143  144            6.8           3.2            5.9           2.3   
144  145            6.7           3.3            5.7           2.5   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
140  Iris-virginica  
141  Iris-virginica  
142  Iris-virginica  
143  Iris-virginica  
144  Iris-virginica  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

8. Tampilkan dataset 10-25

In [ ]:
# Menampilkan dataset 10-25
data.iloc[10:26]
# atau
# data[10:26]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa

9.  Tampilkan nama semua kolom pada data

In [ ]:
# menampilkan nama semua kolom pada data
data.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

10. Tampilkan Kolom **"Species"** saja.

In [ ]:
# Menampilkan hanya kolom Species
data[['Species']]

Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

11. Tampilkan kolom **'SepalLengthCm'** dan **'Species'**.

In [ ]:
# Menampilkan kolom SepalLengthCm dan Species
data[['SepalLengthCm','Species']]

SepalLengthCm         Species
0              5.1     Iris-setosa
1              4.9     Iris-setosa
2              4.7     Iris-setosa
3              4.6     Iris-setosa
4              5.0     Iris-setosa
..             ...             ...
145            6.7  Iris-virginica
146            6.3  Iris-virginica
147            6.5  Iris-virginica
148            6.2  Iris-virginica
149            5.9  Iris-virginica

[150 rows x 2 columns]

12. Tampilkan nama kolom dengan index 3


In [ ]:
# menampilkan nama kolom dengan index 3
data.columns[3]

'PetalLengthCm'

13. Tampilkan jumlah baris dan kolom

In [ ]:
# Menampilkan jumlah baris dan kolom
data.shape

(150, 6)

14. Tampilkan info data bunga Iris

In [ ]:
# Menampilkan info data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


15. Tampilkan deskripsi data secara statistik.

In [ ]:
# deskripsi data secara statistik
data.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

16. Tampilkan berapa jumlah data Iris-setosa      , Iris-versicolor dan Iris-virginica.

In [ ]:
# menampilkan jumlah data pernilai pada kolom Species
data['Species'].value_counts()
# atau
# data.value_counts('Species')

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

17. Cek apakah ada nilai Null pada dataframe.

In [ ]:
data.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

18. Cek apakah ada data NaN di dataframe.

In [ ]:
data.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

19. Hapus atribut **Id** dan **Species** kemudian simpan dalam variabel **X**.

In [ ]:
X = data.drop(['Id','Species'], axis =1) # axis =1 untuk mengidentifikasi kolom, axis=0 untuk baris
X
# id dibuang karena berfungsi. sedangkan species sebagai target untuk memprediksi bunga apa itu. ini termasuk ke dalam supervised learning

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

20. Tampilkan korelasi **pearson** setiap atribut dari DataFrame **X**.

In [ ]:
X.corr() #pearson default nya. 

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
SepalLengthCm       1.000000     -0.109369       0.871754      0.817954
SepalWidthCm       -0.109369      1.000000      -0.420516     -0.356544
PetalLengthCm       0.871754     -0.420516       1.000000      0.962757
PetalWidthCm        0.817954     -0.356544       0.962757      1.000000

21. Simpan atribut **'Species'** dalam variabel y

In [ ]:
y = data['Species']
y


0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

22. Gunakan modul train_test_split dari sklearn untuk membagi data menjadi data training(x_train), data testing(x_test), label training(y_train), dan label testing(y_test) dengan perbandingan data training dan data testing 80:20.


In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=77) #random state digunakan untuk menjaga 

23. Cetak data training

In [ ]:
print(x_train)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
72             6.3           2.5            4.9           1.5
129            7.2           3.0            5.8           1.6
48             5.3           3.7            1.5           0.2
142            5.8           2.7            5.1           1.9
149            5.9           3.0            5.1           1.8
..             ...           ...            ...           ...
19             5.1           3.8            1.5           0.3
117            7.7           3.8            6.7           2.2
37             4.9           3.1            1.5           0.1
84             5.4           3.0            4.5           1.5
95             5.7           3.0            4.2           1.2

[120 rows x 4 columns]


24. Lakukan prediksi untuk testing x_test, dengan menggunakan modul **LogisticRegression()**.

In [ ]:
logreg = LogisticRegression()
logreg.fit(x_train,y_train)
y_pred = logreg.predict(x_test)



25. Tampilkan akurasi metode **LogisticRegression()** untuk prediksi bunga Iris.

In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy Score Metode Logistic Regression:", accuracy_score(y_test, y_pred))


Accuracy Score Metode Logistic Regression: 0.8666666666666667


26. Tampilkan confusion matrix akurasi metode **LogisticRegression()** untuk prediksi bunga Iris.

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print("Confusion Matrix Metode Logistic Regression:", confusion_matrix(y_test, y_pred))

Confusion Matrix Metode Logistic Regression: [[ 9  0  0]
 [ 0  7  1]
 [ 0  3 10]]


25. Lakukan prediksi untuk testing x_test, dengan menggunakan modul **Naive Bayes Gausian()**.

In [ ]:
gnb = GaussianNB()
gnb.fit(x_train,y_train)
y_pred = gnb.predict(x_test)



26. Tampilkan akurasi metode **Naive Bayes Gausian()** untuk prediksi bunga Iris.

In [ ]:
print("Accuracy Score Metode Naive bayes :", accuracy_score(y_test, y_pred))

Accuracy Score Metode Naive bayes : 0.8666666666666667


27. Tampilkan confusion matrix metode Naive Bayes Gausian() untuk prediksi bunga Iris.

In [ ]:
print("Confusion Matrix Metode Naive Bayes :", confusion_matrix(y_test,y_pred))

Confusion Matrix Metode Naive Bayes : [[9 0 0]
 [0 8 0]
 [0 4 9]]


28. Lakukan prediksi untuk testing x_test, dengan menggunakan modul **KNeighborsClassifier()** dengan metode jarak Minkowski dan nilai n = 3.

In [ ]:
knn = KNeighborsClassifier(n_neighbors=3, p=3) #nilai p itu parameter, nah default untuk minkowski itu angka 3 keatas. setiap angka beda2 outputnya, jadi harus cari yang terbaik itu brp
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)
#kkn itu lebih baik nilai n nya ganjil agar bisa lebih mudah diprediksi. misal ada 3 vote, A ada 2 dan B ada 1. maka yang diambil A


29. Tampilkan akurasi metode **KNeighborsClassifier()** untuk prediksi bunga Iris.

In [ ]:
print("Accuracy Score Metode KNN :",accuracy_score(y_test, y_pred))


Accuracy Score Metode KNN : 0.9


30. Tampilkan confusion matrix metode k-NN untuk prediksi bunga Iris.

In [ ]:
print("Confusion Matrix Metode KNN :", confusion_matrix(y_test,y_pred))


Confusion Matrix Metode KNN : [[ 9  0  0]
 [ 0  7  1]
 [ 0  2 11]]


31. Jika ada bunga iris dengan Panjang Sepal 0.5, Panjang Petal 0.4, Lebar Sepal 0.7 dan Lebar Petal 0.8, lakukan klasifikasi termasuk jenis Iris Apa?*(ini termasuk data validasi)*


In [ ]:
# logreg = LogisticRegression()
# logreg.fit(x_train,y_train)
# logreg_coba = logreg.predict([[0.5,0.7,0.4,0.8]])

# logreg.fit(x_train,y_train)
coba = ([[0.5,0.7,0.4,0.8]])
logreg.predict(coba)



/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array(['Iris-setosa'], dtype=object)

In [ ]:
# knn.fit(x_train,y_train)
coba = ([[0.5,0.7,0.4,0.8]])
knn.predict(coba)


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array(['Iris-setosa'], dtype=object)

In [ ]:
# gnb.fit(x_train,y_train)
coba = ([[0.5,0.7,0.4,0.8]])
gnb.predict(coba)


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array(['Iris-versicolor'], dtype='<U15')

## Setelah dilakukan menggunakan 3 model, 2 klasifikasi menunjukan termasuk jenis bunga iris setosa.

In [ ]:
sepal_length = float(input('Masukan panjang sepal : '))
sepal_width = float(input('Masukan lebar sepal : '))
petal_length = float(input('Masukan panjang petal : '))
petal_width = float(input('Masukan lebar petal : '))

iris_class = knn.predict([[sepal_length, sepal_width, petal_length, petal_width]])

print('Klasifikasi tergolong bunga = ', iris_class[0])

Masukan panjang sepal : 4
Masukan lebar sepal : 2.4
Masukan panjang petal : 0.3
Masukan lebar petal : 0.7
Klasifikasi tergolong bunga =  Iris-setosa


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
