<a href="https://colab.research.google.com/github/roannarum/Data-Practice/blob/main/Normalisasi_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

list = [3.24,-1.58,-0.35,1.68,-1.27,2.46,1.70,1.23,1.46,1.02]
data = np.array(list)

In [2]:
data_simplefeaturescalling = data/data.max()

In [14]:
data_simplefeaturescalling 

array([ 1.        , -0.48765432, -0.10802469,  0.51851852, -0.39197531,
        0.75925926,  0.52469136,  0.37962963,  0.45061728,  0.31481481])

In [4]:
data_minmax = (data-data.min())/(data.max()-data.min())

In [5]:
data_minmax

array([1.        , 0.        , 0.25518672, 0.67634855, 0.06431535,
       0.83817427, 0.68049793, 0.58298755, 0.63070539, 0.53941909])

In [6]:
data_zscore = (data-data.mean())/data.std()

In [7]:
data_zscore

array([ 1.53849724, -1.71251403, -0.88289912,  0.48630272, -1.50342409,
        1.01239998,  0.4997924 ,  0.18278507,  0.33791632,  0.0411435 ])

In [11]:
from scipy import stats

random = np.random.default_rng()
data = stats.norm.rvs(size=100, random_state = random)
data

array([ 2.56354200e+00, -7.04832708e-02,  1.35357712e+00,  2.06259787e+00,
       -1.65857441e+00, -8.91487039e-04, -1.53234241e+00,  5.29256115e-01,
        8.42243685e-01, -7.21767054e-01, -1.20559286e+00,  8.95656452e-01,
        1.31594480e-01,  6.97415160e-01,  1.42184583e+00, -1.32053042e+00,
       -4.09634522e-01,  6.10243499e-01, -3.76967517e-01, -6.18934490e-01,
        4.98693578e-01, -1.68880634e+00, -5.99946683e-01, -8.02797087e-01,
       -1.10166178e+00, -1.88846948e+00,  1.82209520e+00,  1.72007866e+00,
       -3.71158044e-02, -1.04055237e-01,  7.90098393e-02,  1.32433422e+00,
        1.58352653e+00, -2.21443005e+00,  1.74437853e-01,  3.35992502e-01,
       -4.35777260e-01,  5.72436890e-01,  1.90936757e+00, -6.07250601e-01,
        1.16420920e-01, -6.73499246e-01,  9.22408382e-02, -6.17017526e-01,
        1.04186736e+00, -9.37914322e-01,  1.39586080e-01, -1.17341192e+00,
       -2.22198522e+00, -2.67503072e-01, -8.79400839e-02, -3.06431519e-01,
       -2.50278439e-01, -

In [13]:
from scipy.stats import kstest

kstest(data, 'norm')

KstestResult(statistic=0.07449351991247088, pvalue=0.6088489082749593)

In [16]:
# normalisasi dengan simple feature scalling
data_simplefeaturescalling = data/data.max()


In [ ]:
data_simplefeaturescalling

In [18]:
kstest(data_simplefeaturescalling, 'norm')

KstestResult(statistic=0.22300245096551788, pvalue=7.5310690211704e-05)

# Diperoleh p-value > 0,05, maka data belum normal

In [19]:
data_minmax = (data-data.min())/(data.max()-data.min())

In [20]:
kstest(data_minmax, 'norm') #

KstestResult(statistic=0.5087784620200366, pvalue=1.5979398544781537e-24)

# Diperoleh p-value > 0,05, maka data belum normal

In [21]:
data_zscore = (data-data.mean())/data.std()

In [22]:
kstest(data_zscore, 'norm') #Diperoleh p-value > 0,05, maka data belum normal

KstestResult(statistic=0.06390493900194816, pvalue=0.7845417997861245)

# Diperoleh p-value > 0,05, maka data belum normal